---
# TODO
# Asserts:
#   All env vars required exist
# Seperate this into three parts
#   main.yml ==> install.yml to setup the app
#   create update.yml to update/manage the app
#   create backup.yml to setup borg and/or xfsdump
# create some test cases to
#   validate this
#   check that backups are working

  - name: gather_facts
    gather_facts:
    when:
      - ansible_facts is undefined
  
  - name: Install Podman
    ansible.builtin.package:
      name: podman
      state: present
  
  - name: Stat heimdall directory - Check if it exists
    stat:
      path: "{{ HEIMDALL_VOLUME_DIR }}"
    register: heimdall_volume_dir_stat

  - name: Create volume if it doesn't exist
    block:
      - name: Create heimdall LV
        community.general.lvol:
          vg: "{{ HEIMDALL_LVM_VG_NAME }}"
          lv: "{{ HEIMDALL_LVM_LV_NAME }}"
          size: "{{ HEIMDALL_VOLUME_MIN_SIZE }}"
      - name: XFS on heimdall LV
        community.general.filesystem:
          fstype: xfs
          dev: "/dev/mapper/{{ HEIMDALL_LVM_VG_NAME }}-{{ HEIMDALL_LVM_LV_NAME }}"
      - name: Create heimdall volume folder
        ansible.builtin.file:
          path: "{{ HEIMDALL_VOLUME_DIR }}"
          state: directory
          mode: '711'
      - name: Add heimdall LV to fstab & mount
        ansible.posix.mount:
          path: "{{ HEIMDALL_VOLUME_DIR }}"
          src: "/dev/mapper/{{ HEIMDALL_LVM_VG_NAME }}-{{ HEIMDALL_LVM_LV_NAME }}"
          fstype: xfs
          opts: defaults
          state: mounted
          boot: true
    when:
      - not heimdall_volume_dir_stat.stat.exists

  - name: Grow heimdall partition
    community.general.lvol:
      vg: "{{ HEIMDALL_LVM_VG_NAME }}"
      lv: "{{ HEIMDALL_LVM_LV_NAME }}"
      size: "{{ HEIMDALL_VOLUME_MIN_SIZE }}"
      resizefs: true
      shrink: false
  
  - name: Create heimdall service account
    ansible.builtin.user:
      name: "{{ HEIMDALL_SERVICE_ACCOUNT }}"
      shell: '/sbin/nologin'

  - name: Change owner of heimdall volume 
    ansible.builtin.file:
      path: "{{ HEIMDALL_VOLUME_DIR }}"
      owner: "{{ HEIMDALL_SERVICE_ACCOUNT }}"
      group: "{{ HEIMDALL_SERVICE_ACCOUNT }}"
      mode: '711'
      state: directory

  - name: Podman pull latest linuxserver/heimdall
    containers.podman.podman_image:
      name: 'lscr.io/linuxserver/heimdall'
      tag: 'latest'

# https://serverfault.com/a/1122361
  - name: "Get user ID for service account"
    ansible.builtin.getent:
      database: passwd

  # Required for podman
  - name: Sebool enable container_manage_cgroup
    ansible.posix.seboolean:
      name: container_manage_cgroup
      persistent: true
      state: true

  # Required for nginx
  - name: Sebool enable httpd_can_network_connect
    ansible.posix.seboolean:
      name: httpd_can_network_connect
      persistent: true
      state: true

  - name: "Copy heimdall systemd service"
    ansible.builtin.template:
      src: "{{ role_path }}/templates/heimdall.service.j2"
      dest: "/etc/systemd/system/heimdall.service"
    notify: "Update heimdall service"

  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Make my default ssl cert dir
    ansible.builtin.file:
      path: "/etc/nginx/certs"
      state: 'directory'
      owner: 'root'
      group: 'root'
      mode: '700'

  - name: Copy SSL Cert
    ansible.builtin.copy:
      src: "{{ HEIMDALL_SSL_CERT_PATH_COPY }}"
      dest: "{{ HEIMDALL_SSL_CERT_PATH }}"
    notify: Restart nginx
    when:
      - HEIMDALL_SSL_CERT_PATH_COPY is defined

  - name: Copy SSL Key
    ansible.builtin.copy:
      src: "{{ HEIMDALL_SSL_KEY_PATH_COPY }}"
      dest: "{{ HEIMDALL_SSL_KEY_PATH }}"
    notify: Restart nginx
    when:
      - HEIMDALL_SSL_KEY_PATH_COPY is defined

  - name: Copy heimdall nginx template
    ansible.builtin.template:
      src: "{{ role_path }}/templates/nginx.conf.j2"
      dest: /etc/nginx/conf.d/heimdall.conf
    notify: Restart nginx
  
  - name: Add https through firewall
    ansible.posix.firewalld:
      service: https
      permanent: true
      state: enabled
    notify: Reload firewalld

  - name: Add http through firewall
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: enabled
    notify: Reload firewalld


# TODO Check that HEIMDALL_URL returns a 200 or a 300
# TODO BACKUPS